# Generated by Django 4.1.4 on 2022-12-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_address_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
