# Generated by Django 4.1.4 on 2023-01-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_status_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
